### ISSUE TITLE
Choose a proper database in order to handle the requirement to have customers choosing their own form schemas

### ISSUE THREAD

**Issue by puzzledbytheweb** [reach4help/covidhelphub-backend#3]
Our customers need to create their own forms so they can't be bound to a rigid schema defined by us. We need to play around with noSQL and SQL databases to find the best suit for this. 

I'm thinking about trying our PostgresSQL in the SQL realm and in MongoDB in the noSQL realm, just because those are the two DBs I'm most acquainted with.

**Comment by edmkitty** [comment]
I am also familiar with PostgreSQL and I think it's pretty popular, so my vote goes to PostgreSQL. I have no objection to mongo either. I am also familiar with Redis, but that is a key-value store instead of a document store so I'm not sure it will solve the same use cases as mongo.
